### ISSUE TITLE
Build fails miserably against WPGraphQL Schema

### ISSUE THREAD

**Issue by richardaubin** [Husqvik/GraphQlClientGenerator#153]
[wpgraphql_schema.txt](https://github.com/Husqvik/GraphQlClientGenerator/files/14173582/wpgraphql_schema.txt)
I've attached the restult of the introspection query that you provided in [https://github.com/Husqvik/GraphQlClientGenerator/issues/108](url)

![image](https://github.com/Husqvik/GraphQlClientGenerator/assets/37956997/b2dd1277-07fb-44c0-934e-9c32819a8f16)

**Comment by Husqvik** [comment]
Thanks for reporting. I'll hope to find some time during this week to fix these.

**Comment by richardaubin** [comment]
No problem.  The first group of errors are related to the Enum generation.  The enums with errors are of the _0000x0000 type.  When the enums are generated, the _ is removed and produces an invalid enum name starting with integers. The _ should be kept when the name is created.

And not sure how to explain the other ones :)

**Comment by Husqvik** [comment]
It's at least three issues:

1. enum names - can be temporarily solved by using `EnumValueNaming = EnumValueNamingOption.Original` option
2. interfaces not generated because containing only deprecated fields - can be temporarily solved by using `IncludeDeprecatedFields = true`
3. interface inherited from another interface contains a field of same name but different type - there is no temporary solution for this issue

**Comment by Husqvik** [comment]
Which tool do you use to define/build the schema? Because the metadata contains some invalid information. For example GraphQL doesn't support interface inheritance but in your schema there are 57 interfaces defined as inheriting from other interface. This is part of the third issue, the easier.

Another thing is that a type implements multiple interfaces with same member name but different type (interface). Without containing that definition on the object type. Will need to explore how GraphQL behaves in such case.

**Comment by richardaubin** [comment]
Here's the SDL schema if that will help... It's not my own and created by a third party.

[wpgraphql.zip](https://github.com/Husqvik/GraphQlClientGenerator/files/14234879/wpgraphql.zip)

**Comment by Husqvik** [comment]
Thanks. I think I have enough information to fix the problem.

**Comment by Husqvik** [comment]
[WordpressSchema.zip](https://github.com/Husqvik/GraphQlClientGenerator/files/14325223/WordpressSchema.zip)

**Comment by Husqvik** [comment]
fixed in https://www.nuget.org/packages/GraphQlClientGenerator/0.9.19
