### ISSUE TITLE
Deserialise graphql response interface

### ISSUE THREAD

**Issue by CyrilleFormont** [Husqvik/GraphQlClientGenerator#24]
Hi there,
I'm using a graphql Interface, I'm getting all the classes related in the generated code but also I got a class named as a base class.

```
public interface IContentSnippetInterface
    {
        int? Id { get; set; }
        int? Sort { get; set; }
    }

    public class ContentSnippetInterface : IContentSnippetInterface
    {
        public int? Id { get; set; }
        public int? Sort { get; set; }
    }

    public class ContentSnippetTextType : IContentSnippetInterface
    {
        public int? ContainerId { get; set; }
        public int? Id { get; set; }
        public int? Sort { get; set; }
        public string Text { get; set; }
    }
 public class ContentSnippetVideoType : IContentSnippetInterface
    {
        public AssetType Asset { get; set; }
        public string AssetId { get; set; }
        public int? ContainerId { get; set; }
        public int? Id { get; set; }
        public int? Sort { get; set; }
        public int? StartAt { get; set; }
    }
```

After deserialisation :

`            
var section = graphQLResponse.GetDataFieldAs<ContentSectionQueries>("contentSection").GetContentSection; 
`

In the returned object, my list of object is as the class "ContentSnippetInterface", at this point it's impossible to cast it into a  "VideoType" or a "TextType" as it's already a class and not an interface, all data are lost so far.

Regards,

Cyrille.

**Comment by Husqvik** [comment]
I don't know how your GraphQL schema looks like. The implemented interfaces in C# are more meant for the input objects (so you can use concrete object returned as field in some response as input parameter of other query that requires interface the object implements), that's why I also generate `ContentSnippetInterface` just to provide the values that can be used (if you don't have concrete object). If the response field is of interface field it cannot be resolved which concrete type is behind therefore it should be returned as object/dynamic type.

Now I just got an idea to generate classes as partial so you can add your own code to do the mapping to concrete type without messing up with generated code.
