### ISSUE TITLE
Custom Scalar Types and Type Mapping in GraphQlQueryParameter

### ISSUE THREAD

**Issue by imdbere** [Husqvik/GraphQlClientGenerator#80]
Hi,

I would like to create a query with different parameters that contain custom types mapped by a ScalarFieldTypeMappingProvider and an ID type mapped by IdTypeMapping.
I know that i can map parameter types to the GraphQL type manually by creating the parameter like this,
`new GraphQlQueryParameter<DateTime>("time", "DateTime", time)`
but i thought it would be nice to not have this additional source of errors, since the mapping is already specified in another place anyway.

Is something like this possible ?
Thanks !

**Comment by Husqvik** [comment]
you mean you'd like to avoid specifying `"DateTime"` GraphQL scalar type explicitly similar like the type is inferred automatically for simple input types where just `new GraphQlQueryParameter<InputType>("parameter", inputType)` can be used?

**Comment by imdbere** [comment]
Yes, exactly

**Comment by Husqvik** [comment]
Ok, I think I have idea how to fix it. Will try to check it out during weekend. Meanwhile there is `GraphQlTypes` class with all GraphQL type names as constants.

**Comment by Husqvik** [comment]
The new implementation should support recognizing both built in and custom types, both nullable and non-nullable as well as collections (even nested ones).

Since custom scalar mapping can be different for for different members/types (very atypical and not recommended) the first resolved type will be used.

Could you test it before I make new Nuget package?
