### ISSUE TITLE
BasesClasses class isn't created during generation only data classes.

### ISSUE THREAD

**Issue by AngryTester95** [Husqvik/GraphQlClientGenerator#98]
Good afternoon!

I have tried to generate only data classes with the next configuration:

 ```csharp
var config = new GraphQlGeneratorConfiguration
{
	CommentGeneration = CommentGenerationOption.Disabled,
	CSharpVersion = CSharpVersion.Compatible,
	JsonPropertyGeneration = JsonPropertyGenerationOption.Always,
	IncludeDeprecatedFields = true,
	PropertyGeneration = PropertyGenerationOption.AutoProperty,
};

GenerationContext context = new MultipleFileGenerationContext(
	schema: schema,
	outputDirectory: Path.Combine(Directory.GetCurrentDirectory(), "./../../../../Temp.Models/Models/Pm"),
	projectFileName: "Temp.Models",
	@namespace: "Temp.Models",
	objectTypes: GeneratedObjectType.DataClasses);
```

Classes have been successfully generated, but I see, that some part of required classes/intefaces is not generated (for input object):

![image](https://user-images.githubusercontent.com/82048855/135755146-176a139c-c200-44b8-976f-bfa064619760.png)

As I can see BaseClass.cs is generated only if `GenerationContext.ObjectTypes` has `GeneratedObjectType.QueryBuilders` flag, but seems that it isn't correct.

**Comment by Husqvik** [comment]
Thanks, this is unintended. It's due to the input object values handling where we need to distinguish `null` and `undefined`. So after that change some of the base classes are needed even for data class to be compiled. I added `BaseClasses` object type option so it it's possible to generate them on demand. But for common use it basically doesn't make sense to generate anything else than all. I used it just for testing where I was focused to particular types.

Let me know if you need an updated nuget package.
